version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ENV=development
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  frontend:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./static:/usr/share/nginx/html  # Zorgt ervoor dat de frontend bestanden beschikbaar zijn voor nginx
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
